### ISSUE TITLE
Pressing PAGEUP in the top page should move cursor to first line

### ISSUE THREAD

**Issue by tombh** [tombh/novim-mode#1]

**Comment by stfl** [comment]
Ohne test

```
innoremap <pageup> <c-o><c-b>
```

**Comment by tombh** [comment]
Danke, Ich vershuche jetzt aber nichts :(

**Comment by tombh** [comment]
Fixed with: https://github.com/tombh/novim-mode/commit/79bd6b4273325f891d2fcdb2a79ede59e313e414#diff-fa56c8466d1a253f7740d0c8e58885f1R265
