### ISSUE TITLE
Breakage on neovim 0.8.0

### ISSUE THREAD

**Issue by omentic** [tombh/novim-mode#15]
See https://github.com/neovim/neovim/pull/18547.

Currently looking into fixing this but likely won't have time until the weekend. It seems the maintainers are well aware of people using this and so have provided some example scripts as workarounds.

In principle this shouldn't be an issue because of `autocmd`, we may just have to tweak existing commands to explicitly enter insert mode again.

**Comment by omentic** [comment]
Ah nevermind, I see you already fixed this! I just haven't updated my plugins in a while...

**Comment by tombh** [comment]
Hey, but glad you're enjoying the plugin and are keen to keep us up to date with changes! ❤️
