### ISSUE TITLE
Conflict with telescope

### ISSUE THREAD

**Issue by Lassebq** [tombh/novim-mode#18]
Since novim-mode is always active, it tampers with UI plugins like telescope. Due to that, it forces you into insert mode by default and you need to Shift+Esc out of it. Is there any way to disable novim-mode until you're in the editor environment?

**Comment by tombh** [comment]
Oh, I use Telescope all the time and I don't think I've ever seen that. Or maybe I'm just missing out on loads of Telescope behaviour!? Is there an easy way to reproduce an example of the problem you're seeing?

**Comment by Lassebq** [comment]
Ok, well, I was wrong about it forcing you into insert mode, because it seems it's already in it by default. But my problem is that you need to press Shift-Esc instead of Esc in order to change focus from the search field to the list of items

**Comment by Lassebq** [comment]
I believe `insert mode` = focus on the search box and `normal mode` = focus on the list

**Comment by tombh** [comment]
I might be misunderstanding. But I just use the up and down keys to cycle through the list items. The only thing I use `ESC` for is closing Telescope itself.

I have my dotfiles online if that helps, eg: here's the `ESC` binding https://github.com/tombh/dotfiles/blob/master/nvim/lua/_telescope.lua#L46

**Comment by Lassebq** [comment]
Hmmm, I'm guessing it's an issue with another plugin... I'll close the issue for now
