### ISSUE TITLE
Scrolling deletes the last line.

### ISSUE THREAD

**Issue by captain0xff** [tombh/novim-mode#8]
I am using novim with neovim in termux. But there scrolling or more clearly swiping (same as scrolling) deletes the last line instead. It behaves normally if this plugin is disabled. Thank you.

**Comment by tombh** [comment]
Thanks for the feedback! I can't begin to think what the issue might be here. What do you mean by deleting the last line? Does it delete the status line? Or the last line of the buffer? Could a temporary hack be to increase the amount of empty lines at the end of the buffer?

**Comment by captain0xff** [comment]
Yes. I mean the last line of the buffer. And if I keep on scrolling it deletes all the lines one by one. And from what I have understood this is due to the remaping of scrolling events i.e ctrl-e and ctrl-y. So ig if I can remap them back it will work normally. But I am unable to do that. @tombh

**Comment by captain0xff** [comment]
Or somehow stop novim from mapping ctrl-e and ctrl-y.

**Comment by tombh** [comment]
Ah right, interesting. Well have you tried disabling each group of novim features? The instructions are here https://github.com/tombh/novim-mode#interoperability

**Comment by captain0xff** [comment]
Found. The problem is with the copy pasting bindings.

**Comment by captain0xff** [comment]
This one let g:novim_mode_use_copypasting = 1

**Comment by captain0xff** [comment]
But the copy pasting is one of the most important one. So I can't keep them disabled forever.

**Comment by tombh** [comment]
Ok! We're getting somewhere. So these are the lines that get disabled with `let g:novim_mode_use_copypasting = 0`: 

```vim
    " One of those curious features of Vim: without `onemore` when pasting
    " at the end of a line, pasted text gets put *before* the cursor.
    set virtualedit=onemore
    " NB. All these use the system clipboard.
    inoremap <C-V> <C-O>:call novim_mode#Paste()<CR>
    " The odd <Space><Backspace> here is because one-off Normal Mode commands
    " don't seem to work as expected when some text is selected. Also just
    " using <Backspace> on its own seems to cause weird behaviour too.
    snoremap <C-V> <Space><Backspace><C-O>:call novim_mode#Paste()<CR>
    cnoremap <C-V> <C-R>"
    snoremap <C-C> <C-O>"+ygv
    inoremap <C-C> <C-O>"+Y
    snoremap <C-X> <C-O>"+xi
    inoremap <C-X> <C-O>"+dd
    " Select word under cursor
    inoremap <C-D> <C-O>viw<C-G>
    " Select current line
    inoremap <C-L> <C-O>V<C-G>
    " Append next line to selection
    snoremap <C-L> <C-O>gj

    " CTRL-A for selecting all text
    inoremap <C-A> <C-O>gg<C-O>gH<C-O>G
    snoremap <C-A> <C-O><C-C>gggH<C-O>G
```

You could try adding them manually in your own config. Hopefully the specific line that causes the bug isn't something that you particularly need. Please let us know if you find it

**Comment by captain0xff** [comment]
Ok. Found it. This is the line that causes it.
```inoremap <C-X> <C-O>"+dd```
Can you kindly tell what is the purpose of this line?

**Comment by tombh** [comment]
It's a shortcut for cutting a whole line into the clipboard. So when you're in `INSERT` mode and press `CTRL`+ `x`, the line under the cursor is deleted and placed in the clipboard. It's not that useful I don't think, it's a convenience. I don't actually ever use it myself

**Comment by captain0xff** [comment]
Oh. I see. And yes I too think that its not that useful. I mean I can use novim without this functionality. 
And thanks a lot for making this plugin and its very very useful for me. Actually I am just a normal coder not that big fan of vim/emacs and in pc use the other ides. But in android there's no option the other ides gui ides are not at all useable(full of ads) and there vim proves to be a big gem(it offers much more features). Thanks again. ;). I think this issue can be closed now.

**Comment by tombh** [comment]
I've made a note in the code about it. I think I'm going to disable it by default. There's some other things I want to disable too, so maybe I'll do them all at the same time.

That's great you appreciate this plugin! Thank you 😁 Yeah I totally agree, I'm not a big fan of Vim either, at least Vim modal editing. It's just that the editor is by far the best terminal editor. We shouldn't have to be modal editing experts to take advantage of all the other great things about it

**Comment by captain0xff** [comment]
Yes. True if not only best terminal editor it can even beat the most of the gui editors also. But the main problem with it is its keybindings that scares away most people. No editor in the world can beat it in features/ram_usage ratio. But the keybindings...
And currently I am just forking your repo and will wait for you to disable them in the next version. :]

**Comment by tombh** [comment]
Indeed, the best editor, full stop! It would be great if this plugin could be well known, so everybody knew they could just have a "normal" vim editor if they wanted.

Ok I'll get the main repo updated ASAP

**Comment by captain0xff** [comment]
Wonderful. Thanks.
