### ISSUE TITLE
Neovim Terminal not opening in insert mode.

### ISSUE THREAD

**Issue by captain0xff** [tombh/novim-mode#9]
I am using the neovim terminal in termux to execute python code. And wanted that the terminal to open in insert mode so that I can input. The keymap I use for this purpose is:-
```inoremap <F4> <C-o>:w<CR><C-o>:term python %<CR>```
And it works fine with the novim plugin disabled but if the plugin is enabled the terminal opens in nornal mode and I can't input any value until I jump to insert mode. 
Strangely this behaviour is ironic to novim as its made for keeping things in insert mode but in this case it does just the opposite. 
And I have tried to debug the issue by setting these options to false
```
let g:novim_mode_use_general_app_shortcuts = 1
let g:novim_mode_use_pane_controls = 1
let g:novim_mode_use_copypasting = 1
let g:novim_mode_use_indenting = 1
let g:novim_mode_use_finding = 1
let g:novim_mode_use_undoing = 1
let g:novim_mode_use_text_tricks = 1

" Small fixes to HOME and PAGEUP behaviour
let g:novim_mode_use_editor_fixes = 1
" Allows scrolling through wrapped lines one visual line at a time
let g:novim_mode_use_better_wrap_navigation = 1
```
But the problem still persists even if I set all the options to 0 so ig the problem is with some core thing.

**Comment by tombh** [comment]
Thanks, nice find. I've pushed a fix, does it help?

**Comment by captain0xff** [comment]
Yes thank you. It fixes the issue.

**Comment by tombh** [comment]
Great
